version: '3.3'
services:
  database: 
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORTS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: ${PG_ADMIN_IMAGE}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - ${PGADMIN_PORT}